<!DOCTYPE html>
<html>
  <head>
    <title>ExUnit.Assertions</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/style.css" type="text/css" media="screen" charset="utf-8" />

    <script type="text/javascript" charset="utf-8">
      relpath = '';
      if (relpath != '') relpath += '/';
    </script>

    <script type="text/javascript" charset="utf-8" src="js/jquery.js"></script>
    <script type="text/javascript" charset="utf-8" src="js/app.js"></script>
  </head>

  <body>
    <script type="text/javascript" charset="utf-8">
      if (window.top.frames.main) document.body.className = 'frames';
    </script>

    <div id="content">
      <h1>
        ExUnit.Assertions
        
      </h1>

      
        <div id="moduledoc" class="docstring">
          <p>This module contains a set of assertion functions that are
imported by default into your test cases.</p>

<p>In general, a developer will want to use the general
<code>assert</code> macro in tests. This macro tries to be smart
and provide good reporting whenever there is a failure.
For example, <code>assert some_fun() == 10</code> will fail (assuming
<code>some_fun()</code> returns 13):</p>

<pre><code>Expected 10 to be equal to 13
</code></pre>

<p>This module also provides other convenience functions
like <code>assert_in_delta</code> and <code>assert_raise</code> to easily handle other
common cases such as checking a floating point number or handling exceptions.</p>

        </div>
      

      <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L20" target="_blank" class="view_source">Source</a>

      

      
        <h2 id="functions_summary">Functions summary</h2>
        <table class="summary">
          <tr>
  <td class="summary_signature"><a href="#assert/2">assert(expected, message)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the <code>expected</code> value is true.
If it fails, raises the given <code>message</code>.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#assert/4">assert(value, expected, actual, content)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the <code>expected</code> value is true.
If it fails, it raises an expectation error
using the given <code>expected</code> and <code>actual</code> values.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#assert_in_delta/4">assert_in_delta(expected, received, delta, message // nil)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the <code>expected</code> and <code>received</code> are within <code>delta</code>.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#assert_raise/2">assert_raise(exception, function)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the <code>exception</code> is raised during <code>function</code> execution.
Returns the rescued exception, fails otherwise.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#assert_raise/3">assert_raise(exception, message, function)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the <code>exception</code> is raised during <code>function</code> execution with
the <code>expected_message</code>. Returns the rescued exception, fails otherwise.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#flunk/1">flunk(message // &quot;Flunked!&quot;)</a></td>
  
    <td class="summary_synopsis"><p>Fails with a message.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#refute/2">refute(not_expected, message)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the <code>not_expected</code> value is <code>nil</code> or <code>false</code>.
In case it is a truthy value, raises the given message.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#refute_in_delta/4">refute_in_delta(expected, received, delta, message // nil)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the <code>expected</code> and <code>received</code> are not within <code>delta</code>.</p>
</td>
  
</tr>

        </table>
      

      
        <h2 id="macros_summary">Macros summary</h2>
        <table class="summary">
          <tr>
  <td class="summary_signature"><a href="#assert/1">assert(expected)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the <code>expected</code> value is true.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#assert_receive/3">assert_receive(expected, timeout // 100, message // nil)</a></td>
  
    <td class="summary_synopsis"><p>Asserts a message was or is going to be received. Unlike
<code>assert_received</code>, it has a default timeout of 100 milliseconds.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#assert_received/2">assert_received(expected, message // nil)</a></td>
  
    <td class="summary_synopsis"><p>Asserts a message was received and is in the current process&#39; mailbox.
Timeout is set to 0, so there is no waiting time.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#catch_error/1">catch_error(expression)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the given <code>expression</code> will cause an error.
Returns the error or fails otherwise.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#catch_exit/1">catch_exit(expression)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the given <code>expression</code> will exit.
Returns the exit status/message or fails otherwise.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#catch_throw/1">catch_throw(expression)</a></td>
  
    <td class="summary_synopsis"><p>Asserts the given <code>expression</code> will throw a value.
Returns the thrown value or fails otherwise.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#refute/1">refute(expected)</a></td>
  
    <td class="summary_synopsis"><p>Refutes the <code>expected</code> value is true.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#refute_receive/3">refute_receive(not_expected, timeout // 100, message // nil)</a></td>
  
    <td class="summary_synopsis"><p>Asserts a message was not received and won&#39;t be within
the <code>timeout</code> period.</p>
</td>
  
</tr>
<tr>
  <td class="summary_signature"><a href="#refute_received/2">refute_received(not_expected, message // nil)</a></td>
  
    <td class="summary_synopsis"><p>Asserts a message was not received (i.e. it is not in the current process mailbox).
The <code>not_expected</code> argument must be a match pattern.</p>
</td>
  
</tr>

        </table>
      

      

      

      
        <div id="functions_details" class="details_list">
          <h2>Functions</h2>
          <div class="detail">
  <p class="signature" id="assert/2">
    <strong>assert(expected, message)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the <code>expected</code> value is true.
If it fails, raises the given <code>message</code>.</p>

<h2>Examples</h2>

<pre><code>assert false, &quot;it will never be true&quot;
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L221" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="assert/4">
    <strong>assert(value, expected, actual, content)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the <code>expected</code> value is true.
If it fails, it raises an expectation error
using the given <code>expected</code> and <code>actual</code> values.</p>

<h2>Examples</h2>

<pre><code>assert this &gt; that, this, that, &quot;more than&quot;
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L236" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="assert_in_delta/4">
    <strong>assert_in_delta(expected, received, delta, message // nil)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the <code>expected</code> and <code>received</code> are within <code>delta</code>.</p>

<h2>Examples</h2>

<pre><code>assert_in_delta 1.1, 1.5, 0.2
assert_in_delta 10, 15, 4
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L369" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="assert_raise/2">
    <strong>assert_raise(exception, function)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the <code>exception</code> is raised during <code>function</code> execution.
Returns the rescued exception, fails otherwise.</p>

<h2>Examples</h2>

<pre><code>assert_raise ArithmeticError, fn -&gt;
  1 + &quot;test&quot;
end
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L343" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="assert_raise/3">
    <strong>assert_raise(exception, message, function)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the <code>exception</code> is raised during <code>function</code> execution with
the <code>expected_message</code>. Returns the rescued exception, fails otherwise.</p>

<h2>Examples</h2>

<pre><code>assert_raise ArithmeticError, &quot;bad argument in arithmetic expression&quot;, fn -&gt;
  1 + &quot;test&quot;
end
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L318" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="flunk/1">
    <strong>flunk(message // &quot;Flunked!&quot;)</strong>
  </p>
  
    <p>Specs:</p>
    <ul class="spec">
      
        <li>flunk(<a href="String.html#t:t/0">String.t</a>) :: no_return</li>
      
    </ul>
  
  <div class="docstring"><p>Fails with a message.</p>

<h2>Examples</h2>

<pre><code>flunk &quot;This should raise an error&quot;
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L515" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="refute/2">
    <strong>refute(not_expected, message)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the <code>not_expected</code> value is <code>nil</code> or <code>false</code>.
In case it is a truthy value, raises the given message.</p>

<h2>Examples</h2>

<pre><code>refute true, &quot;This will obviously fail&quot;
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L437" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="refute_in_delta/4">
    <strong>refute_in_delta(expected, received, delta, message // nil)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the <code>expected</code> and <code>received</code> are not within <code>delta</code>.</p>

<h2>Examples</h2>

<pre><code>refute_in_delta 1.1, 1.2, 0.2
refute_in_delta 10, 11, 2
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L498" target="_blank" class="view_source">Source</a>
  
</div>

        </div>
      

      
        <div id="macros_details" class="details_list">
          <h2>Macros</h2>
          <div class="detail">
  <p class="signature" id="assert/1">
    <strong>assert(expected)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the <code>expected</code> value is true.</p>

<p><code>assert</code> in general tries to be smart and provide good
reporting whenever there is a failure. For example,
<code>assert 10 &gt; 15</code> is going to fail with the message:</p>

<pre><code>Expected 10 to be more than 15
</code></pre>

<h2>Examples</h2>

<pre><code>assert true
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L52" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="assert_receive/3">
    <strong>assert_receive(expected, timeout // 100, message // nil)</strong>
  </p>
  
  <div class="docstring"><p>Asserts a message was or is going to be received. Unlike
<code>assert_received</code>, it has a default timeout of 100 milliseconds.</p>

<p>The given <code>expected</code> argument has to be a pattern.</p>

<h2>Examples</h2>

<pre><code>assert_receive :hello
</code></pre>

<p>Asserts against a larger timeout:</p>

<pre><code>assert_receive :hello, 20_000
</code></pre>

<p>You can also match against specific patterns:</p>

<pre><code>assert_receive { :hello, _ }

x = 5
assert_receive { :count, ^x }
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L270" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="assert_received/2">
    <strong>assert_received(expected, message // nil)</strong>
  </p>
  
  <div class="docstring"><p>Asserts a message was received and is in the current process&#39; mailbox.
Timeout is set to 0, so there is no waiting time.</p>

<p>The given <code>expected</code> argument has to be a pattern.</p>

<h2>Examples</h2>

<pre><code>self &lt;- :hello
assert_received :hello
</code></pre>

<p>You can also match against specific patterns:</p>

<pre><code>self &lt;- { :hello, &quot;world&quot; }
assert_received { :hello, _ }
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L291" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="catch_error/1">
    <strong>catch_error(expression)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the given <code>expression</code> will cause an error.
Returns the error or fails otherwise.</p>

<h2>Examples</h2>

<pre><code>assert catch_error(error 1) == 1
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L411" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="catch_exit/1">
    <strong>catch_exit(expression)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the given <code>expression</code> will exit.
Returns the exit status/message or fails otherwise.</p>

<h2>Examples</h2>

<pre><code>assert catch_exit(exit 1) == 1
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L398" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="catch_throw/1">
    <strong>catch_throw(expression)</strong>
  </p>
  
  <div class="docstring"><p>Asserts the given <code>expression</code> will throw a value.
Returns the thrown value or fails otherwise.</p>

<h2>Examples</h2>

<pre><code>assert catch_throw(throw 1) == 1
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L385" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="refute/1">
    <strong>refute(expected)</strong>
  </p>
  
  <div class="docstring"><p>Refutes the <code>expected</code> value is true.</p>

<p><code>refute</code> in general tries to be smart and provide good
reporting whenever there is a failure.</p>

<h2>Examples</h2>

<pre><code>refute false
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L81" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="refute_receive/3">
    <strong>refute_receive(not_expected, timeout // 100, message // nil)</strong>
  </p>
  
  <div class="docstring"><p>Asserts a message was not received and won&#39;t be within
the <code>timeout</code> period.</p>

<p>The <code>not_expected</code> argument must be a match pattern.</p>

<h2>Examples</h2>

<pre><code>refute_receive :bye
</code></pre>

<p>Refute received with a explicit timeout:</p>

<pre><code>refute_receive :bye, 1000
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L456" target="_blank" class="view_source">Source</a>
  
</div>
<div class="detail">
  <p class="signature" id="refute_received/2">
    <strong>refute_received(not_expected, message // nil)</strong>
  </p>
  
  <div class="docstring"><p>Asserts a message was not received (i.e. it is not in the current process mailbox).
The <code>not_expected</code> argument must be a match pattern.</p>

<p>Timeout is set to 0, so there is no waiting time.</p>

<h2>Examples</h2>

<pre><code>self &lt;- :hello
refute_received :bye
</code></pre>
</div>
  
    <a href="https://github.com/elixir-lang/elixir/blob/v0.11.1/lib/ex_unit/lib/ex_unit/assertions.ex#L472" target="_blank" class="view_source">Source</a>
  
</div>

        </div>
      

      
    </div>
  </body>
</html>
